// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Genie (http://www.github.com/rusith/genie).
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using TestDAL.Infrastructure.Filters.Abstract;

namespace TestDAL.Infrastructure.Filters.Concrete
{
    internal class PropertyFilter : IPropertyFilter
    {
        public string PropertyName { get; set; }
        public string Type { get; set; }
        public object Value { get; set; }
    }
}

